from serviceswidget import ServicesWidget
from specwidget import SpecWidget
from recordswidget import RecordsWidget
from referenceresultswidget import ReferenceResultsWidget
from worksheettemplatelayoutwidget import WorksheetTemplateLayoutWidget