from AccessControl import ClassSecurityInfo
from Products.Archetypes.utils import DisplayList
from Products.Archetypes.Registry import registerWidget
from Products.Archetypes.Widget import TypesWidget
from Products.CMFPlone.i18nl10n import ulocalized_time
from Products.CMFCore.utils import getToolByName
from bika.lims.browser import BrowserView
import json
import plone

class ARResultsInterpretationWidget(TypesWidget):
    _properties = TypesWidget._properties.copy()
    _properties.update({
        'macro': "bika_widgets/arresultsinterpretationwidget",
       # 'helper_js': ("bika_widgets/addresswidget.js",),
       # 'helper_css': ("bika_widgets/addresswidget.css",),
    })

    security = ClassSecurityInfo()

    ''''
    {"theme_advanced_resizing_use_cookie": true,
    "theme_advanced_toolbar_align": "left",
    "link_shortcuts_html": ["\n        <img src=\"img/home.png\" />\n        <a id=\"home\" href=\"https://demo.bikalabs.com\">Home</a>\n        ",
                            "\n        <img src=\"img/folder_current.png\" />\n        <a id=\"currentfolder\" href=\"https://demo.bikalabs.com/clients/client-1/MILK-0055-R01\">Current Folder</a>\n        "],
                            "valid_elements": "code[class|dir|id|style|title],
                                               kbd[class|dir|id|style|title],
                                               aside[class|dir|id|style|title],
                                               img[align|alt|class|dir|height|hspace|id|ismap<ismap|longdesc|name|src|style|title|usemap|vspace|width],title[dir|id],
                                               tt[class|dir|id|style|title],
                                               tr[align|char|charoff|class|dir|id|style|title],
                                               li[class|dir|id|style|title|type],
                                               source[class|dir|id|style|title],
                                               tfoot[align|char|charoff|class|dir|id|style|title],
                                               th[abbr|align|axis|char|charoff|class|colspan|dir|headers|id|nowrap|rowspan|scope|style|title],
                                               td[abbr|align|axis|char|charoff|class|colspan|dir|headers|id|nowrap|rowspan|scope|style|title],
                                               dl[class|compact|dir|id|style|title],
                                               blockquote[cite|class|dir|id|style|title],
                                               big[class|dir|id|style|title],
                                               dd[class|dir|id|style|title],
                                               meter[class|dir|id|style|title],
                                               dt[class|dir|id|style|title],
                                               small[class|dir|id|style|title],
                                               output[class|dir|id|style|title],
                                               div[align|class|dir|id|style|title],
                                               em[class|dir|id|style|title],
                                               datalist[class|dir|id|style|title],
                                               hgroup[class|dir|id|style|title],
                                               meta[content|dir|http-equiv|id|name|scheme],
                                               video[class|dir|id|style|title],
                                               rt[class|dir|id|style|title],
                                               canvas[class|dir|id|style|title],
                                               rp[class|dir|id|style|title],
                                               sub[class|dir|id|style|title],
                                               bdo[class|dir|id|style|title],
                                               sup[class|dir|id|style|title],
                                               progress[class|dir|id|style|title],
                                               body[alink|background|class|dir|id|link|style|text|title|vlink],
                                               acronym[class|dir|id|style|title],
                                               base[href|id|target],
                                               br[class|clear|id|style|title],
                                               address[class|dir|id|style|title],
                                               article[class|dir|id|style|title],
                                               strong[class|dir|id|style|title],
                                               ol[class|compact|dir|id|start|style|title|type],
                                               caption[align|class|dir|id|style|title],
                                               dialog[class|dir|id|style|title],
                                               col[align|char|charoff|class|dir|id|span|style|title|width],
                                               h2[align|class|dir|id|style|title],
                                               h3[align|class|dir|id|style|title],
                                               h1[align|class|dir|id|style|title],
                                               h6[align|class|dir|id|style|title],
                                               h4[align|class|dir|id|style|title],
                                               h5[align|class|dir|id|style|title],
                                               header[class|dir|id|style|title],
                                               table[align|class|dir|id|style|summary|title],
                                               #p[align|class|dir|id|style|title],
                                               span[class|dir|id|style|title],
                                               area[accesskey|alt|class|coords|dir|href|id|nohref|shape|style|tabindex|target|title],
                                               mark[class|dir|id|style|title],
                                               dfn[class|dir|id|style|title],
                                               var[class|dir|id|style|title],
                                               cite[class|dir|id|style|title],
                                               thead[align|char|charoff|class|dir|id|style|title],
                                               head[dir|id|profile],
                                               hr[align|class|dir|id|noshade|size|style|title|width],
                                               ruby[class|dir|id|style|title],
                                               b[class|dir|id|style|title],
                                               colgroup[align|char|charoff|class|dir|id|span|style|title|width],
                                               keygen[class|dir|id|style|title],
                                               ul[class|compact|dir|id|style|title|type],
                                               del[cite|class|datetime|dir|id|style|title],
                                               pre[class|dir|id|style|title|width],
                                               figure[class|dir|id|style|title],
                                               ins[cite|class|datetime|dir|id|style|title],
                                               tbody[align|char|charoff|class|dir|id|style|title],
                                               html[dir|id|xmlns],
                                               nav[class|dir|id|style|title],
                                               details[class|dir|id|style|title],
                                               u[class|dir|id|style|title],
                                               samp[class|dir|id|style|title],
                                               map[class|dir|id|name|title],
                                               a[accesskey|charset|class|coords|dir|href|hreflang|id|name|rel|rev|shape|style|tabindex|target|title|type],
                                               footer[class|dir|id|style|title],
                                               i[class|dir|id|style|title],
                                               q[cite|class|dir|id|style|title],
                                               command[class|dir|id|style|title],
                                               time[class|dir|id|style|title],
                                               audio[class|dir|id|style|title],
                                               section[class|dir|id|style|title],
                                               abbr[class|dir|id|style|title]",
                            "allow_captioned_images": false,
                            "num_of_thumb_columns": 4,
                            "labels": {"label_addnewfile": "Add new File",
                                       "label_browseimage": "Image Browser",
                                       "label_shortcuts": "Shortcuts",
                                       "label_no_anchors": "No anchors in this page",
                                       "label_no_items": "No items in this folder",
                                       "label_styles": "(remove style)",
                                       "label_internal_path": "You are here:",
                                       "label_plain_cell": "Plain cell", "label_print": "Print", "label_style_ldots": "Style...", "label_search_results": "Search results:", "label_lists": "Lists", "label_browser": "Browser", "label_text": "Text", "label_browselink": "Link Browser", "label_paragraph": "Normal paragraph", "label_selection": "Selection", "label_tables": "Tables", "label_addnewimage": "Add new Image"},
                            "image_shortcuts_html": ["\n        <img src=\"img/home.png\" />\n        <a id=\"home\" href=\"https://demo.bikalabs.com\">Home</a>\n        ", "\n        <img src=\"img/folder_current.png\" />\n        <a id=\"currentfolder\" href=\"https://demo.bikalabs.com/clients/client-1/MILK-0055-R01\">Current Folder</a>\n        "],
                            "link_using_uids": true,
                            "skin": "plone",
                            "content_css": "https://demo.bikalabs.com/portal_tinymce/@@tinymce-getstyle",
                            "media_strict": false,
                            "customplugins": ["plonebrowser"],
                            "rooted": false,
                            "gecko_spellcheck": true,
                            "toolbar_width": 440,
                            "thumbnail_size": ["tile", 64, 64],
                            "anchor_selector": "h2,h3",
                            "atd_show_types": "Bias Language,Cliches,Complex Expression,Diacritical Marks,Double Negatives,Hidden Verbs,Jargon Language,Passive voice,Phrases to Avoid,Redundant Expression",
                            "theme_advanced_styles": "[{ title: \"Text\", tag: \"\", className: \"-\", type: \"Text\" },{ title: \"Normal paragraph\", tag: \"p\", className: \" \", type: \"Text\" },{ title: \"Call-out\", tag: \"p\", className: \"callout\", type: \"Text\" },{ title: \"Clear floats\", tag: \"div\", className: \"visualClear\", type: \"Text\" },{ title: \"Heading\", tag: \"h2\", className: \"\", type: \"Text\" },{ title: \"Literal\", tag: \"pre\", className: \"\", type: \"Text\" },{ title: \"Pull-quote\", tag: \"blockquote\", className: \"pullquote\", type: \"Text\" },{ title: \"Subheading\", tag: \"h3\", className: \"\", type: \"Text\" },{ title: \"Selection\", tag: \"\", className: \"-\", type: \"Selection\" },{ title: \"(remove style)\", tag: \"\", className: \"\", type: \"Selection\" },{ title: \"Discreet\", tag: \"span\", className: \"discreet\", type: \"Selection\" },{ title: \"Highlight\", tag: \"span\", className: \"visualHighlight\", type: \"Selection\" },{ title: \"Tables\", tag: \"table\", className: \"-\", type: \"Tables\" },{ title: \"Plain cell\", tag: \"td\", className: \" \", type: \"Tables\" },{ title: \"Fancy listing\", tag: \"table\", className: \"listing\", type: \"Tables\" },{ title: \"Invisible grid\", tag: \"table\", className: \"invisible\", type: \"Tables\" },{ title: \"Even row\", tag: \"tr\", className: \"even\", type: \"Tables\" },{ title: \"Heading cell\", tag: \"th\", className: \"\", type: \"Tables\" },{ title: \"Odd row\", tag: \"tr\", className: \"odd\", type: \"Tables\" },{ title: \"Lists\", tag: \"ul\", className: \"-\", type: \"Lists\" },{ title: \"Lists\", tag: \"ol\", className: \"-\", type: \"Lists\" },{ title: \"Lists\", tag: \"dl\", className: \"-\", type: \"Lists\" },{ title: \"Lists\", tag: \"dl\", className: \" \", type: \"Lists\" },{ title: \"Circle\", tag: \"ul\", className: \"listTypeCircle\", type: \"Lists\" },{ title: \"Definition description\", tag: \"dd\", className: \"\", type: \"Lists\" },{ title: \"Definition term\", tag: \"dt\", className: \"\", type: \"Lists\" },{ title: \"Disc\", tag: \"ul\", className: \"listTypeDisc\", type: \"Lists\" },{ title: \"Lower Alpha\", tag: \"ol\", className: \"listTypeLowerAlpha\", type: \"Lists\" },{ title: \"Lower Roman\", tag: \"ol\", className: \"listTypeLowerRoman\", type: \"Lists\" },{ title: \"Numbers\", tag: \"ol\", className: \"listTypeDecimal\", type: \"Lists\" },{ title: \"Square\", tag: \"ul\", className: \"listTypeSquare\", type: \"Lists\" },{ title: \"Upper Alpha\", tag: \"ol\", className: \"listTypeUpperAlpha\", type: \"Lists\" },{ title: \"Upper Roman\", tag: \"ol\", className: \"listTypeUpperRoman\", type: \"Lists\" },{ title: \"Print\", tag: \"\", className: \"-\", type: \"Print\" },{ title: \"Page break (print only)\", tag: \"div\", className: \"pageBreak\", type: \"Print\" }]", "portal_url": "https://demo.bikalabs.com", "atd_ignore_strings": "Zope,Plone,TinyMCE", "buttons": ["save", "style", "bold", "italic", "justifyleft", "justifycenter", "justifyright", "justifyfull", "bullist", "numlist", "definitionlist", "outdent", "indent", "image", "link", "unlink", "anchor", "tablecontrols", "code", "fullscreen", ""],
                            "theme_advanced_source_editor_height": 400,
                            "theme": "advanced",
                            "livesearch": true,
                            "script_url": "https://demo.bikalabs.com/tiny_mce_gzip.js",
                            "theme_advanced_resize_horizontal": false,
                            "theme_advanced_buttons3": "",
                            "theme_advanced_path_location": "bottom",
                            "table_styles": "Fancy listing=listing;Invisible grid=invisible",
                            "document_url": "https://demo.bikalabs.com/clients/client-1/MILK-0055-R01",
                            "plugins": "advhr,definitionlist,directionality,emotions,fullscreen,inlinepopups,insertdatetime,media,nonbreaking,noneditable,pagebreak,paste,plonebrowser,ploneinlinestyles,plonestyle,preview,print,save,searchreplace,tabfocus,table,visualchars,xhtmlxtras,contextmenu",
                            "body_class": "documentContent template- portaltype-analysisrequest site-Plone section-clients subsection-client-1 subsection-client-1-MILK-0055-R01 icons-on userrole-manager userrole-authenticated userrole-owner",
                            "navigation_root_url": "https://demo.bikalabs.com",
                            "document_base_url": "https://demo.bikalabs.com/clients/client-1/MILK-0055-R01/",
                            "theme_advanced_source_editor_width": 600,
                            "theme_advanced_resizing": true,
                            "table_firstline_th": true,
                            "autoresize": false,
                            "atd_rpc_url": "https://demo.bikalabs.com/@@",
                            "fix_list_elements": false,
                            "body_id": "content",
                            "valid_inline_styles": "text-align,list-style-type,float,padding-left",
                            "atd_rpc_id": "Products.TinyMCE-admin",
                            "theme_advanced_toolbar_location": "top",
                            "language": "en",
                            "contextmenu": true,
                            "theme_advanced_buttons4": "",
                            "entity_encoding": "raw",
                            "directionality": "ltr",
                            "theme_advanced_buttons2": "image,link,unlink,anchor,tablecontrols,code,fullscreen", "inlinepopups_skin": "plonepopup", "mode": "exact", "theme_advanced_buttons1": "save,style,bold,italic,justifyleft,justifycenter,justifyright,justifyfull,bullist,numlist,definitionlist,outdent,indent", "theme_advanced_path": false}
    '''

registerWidget(ARResultsInterpretationWidget,
               title = 'Analysis Request Interpretation Widget',
               description = ('A tabbed pane for Results Interpretation'),
               )