"""configlets used by Bika

$Id: configlets.py 2578 2010-11-29 21:32:14Z anneline $
"""
from Products.bika.config import PROJECTNAME, ManageBika

bika_configlets = (
   {'id': 'bika_labinfo',
    'appId': PROJECTNAME,
    'name': 'Laboratory information',
    'action': 'string:$portal_url/bika_labinfo',
    'category': 'Bika',
    'permission': (ManageBika,),
    'imageUrl': 'lab.png',},

   {'id': 'bika_categories',
    'appId': PROJECTNAME,
    'name': 'Analysis categories',
    'action': 'string:$portal_url/bika_categories',
    'category': 'Bika',
    'permission': (ManageBika,),
    'imageUrl': 'category.png',},

   {'id': 'bika_departments',
    'appId': PROJECTNAME,
    'name': 'Lab departments',
    'action': 'string:$portal_url/bika_departments',
    'category': 'Bika',
    'permission': (ManageBika,),
    'imageUrl': 'department.png',},

   {'id': 'bika_labcontacts',
    'appId': PROJECTNAME,
    'name': 'Lab contacts',
    'action': 'string:$portal_url/bika_labcontacts',
    'category': 'Bika',
    'permission': (ManageBika,),
    'imageUrl': 'contact.png',},

   {'id': 'bika_attachmenttypes',
    'appId': PROJECTNAME,
    'name': 'Attachment Types',
    'action': 'string:$portal_url/bika_attachmenttypes',
    'category': 'Bika',
    'permission': (ManageBika,),
    'imageUrl': 'attachment.png',},

   {'id': 'bika_calctypes',
    'appId': PROJECTNAME,
    'name': 'Calculation Types',
    'action': 'string:$portal_url/bika_calctypes',
    'category': 'Bika',
    'permission': (ManageBika,),
    'imageUrl': 'calculation.png',},

   {'id': 'bika_settings',
    'appId': PROJECTNAME,
    'name': 'Bika settings',
    'action': 'string:$portal_url/bika_settings',
    'category': 'Bika',
    'permission': (ManageBika,),
    'imageUrl': 'setup.png',},

   {'id': 'bika_services',
    'appId': PROJECTNAME,
    'name': 'Analysis services',
    'action': 'string:$portal_url/bika_services',
    'category': 'Bika',
    'permission': (ManageBika,),
    'imageUrl': 'service.png',},

   {'id': 'bika_methods',
    'appId': PROJECTNAME,
    'name': 'Methods',
    'action': 'string:$portal_url/bika_methods',
    'category': 'Bika',
    'permission': (ManageBika,),
    'imageUrl': 'method.png',},

   {'id': 'bika_instruments',
    'appId': PROJECTNAME,
    'name': 'Instruments',
    'action': 'string:$portal_url/bika_instruments',
    'category': 'Bika',
    'permission': (ManageBika,),
    'imageUrl': 'instrument.png',},

   {'id': 'bika_analysisspecs',
    'appId': PROJECTNAME,
    'name': 'Analysis specs',
    'action': 'string:$portal_url/bika_analysisspecs',
    'category': 'Bika',
    'permission': (ManageBika,),
    'imageUrl': 'service.png',},

   {'id': 'bika_arprofiles',
    'appId': PROJECTNAME,
    'name': 'Analysis profiles',
    'action': 'string:$portal_url/bika_arprofiles',
    'category': 'Bika',
    'permission': (ManageBika,),
    'imageUrl': 'service.png',},

   {'id': 'bika_products',
    'appId': PROJECTNAME,
    'name': 'Products',
    'action': 'string:$portal_url/bika_products',
    'category': 'Bika',
    'permission': (ManageBika,),
    'imageUrl': 'product.png',},

   {'id': 'bika_sampletypes',
    'appId': PROJECTNAME,
    'name': 'Sample Types',
    'action': 'string:$portal_url/bika_sampletypes',
    'category': 'Bika',
    'permission': (ManageBika,),
    'imageUrl': 'sampletype.png',},

   {'id': 'bika_standardmanufacturers',
    'appId': PROJECTNAME,
    'name': 'Standard Manufacturers',
    'action': 'string:$portal_url/bika_standardmanufacturers',
    'category': 'Bika',
    'permission': (ManageBika,),
    'imageUrl': 'standardmanufacturer.png',},

   {'id': 'bika_standardstocks',
    'appId': PROJECTNAME,
    'name': 'Standard Stocks',
    'action': 'string:$portal_url/bika_standardstocks',
    'category': 'Bika',
    'permission': (ManageBika,),
    'imageUrl': 'standardstock.png',},

   {'id': 'bika_samplepoints',
    'appId': PROJECTNAME,
    'name': 'Sample Points',
    'action': 'string:$portal_url/bika_samplepoints',
    'category': 'Bika',
    'permission': (ManageBika,),
    'imageUrl': 'samplepoint.png',},

   {'id': 'bika_worksheettemplates',
    'appId': PROJECTNAME,
    'name': 'Worksheet Templates',
    'action': 'string:$portal_url/bika_worksheettemplates',
    'category': 'Bika',
    'permission': (ManageBika,),
    'imageUrl': 'worksheettemplate.png',},
)
