#!/bin/bash

BIKA_BASE=/home/godfrey/workspace/Bika3
PYTHON=/usr/bin/python
COUNTER_FILE=$BIKA_BASE/var/id.counter
LOG_FILE=$BIKA_BASE/var/log/idserver.log
PID_FILE=$BIKA_BASE/var/idserver.pid
PORT=8081

exec $PYTHON $BIKA_BASE/products/bika/scripts/id-server.py \
	-f $COUNTER_FILE \
	-p $PORT \
	-l $LOG_FILE \
	-d $PID_FILE
